server:
  port: 8080

spring:
  application:
    name: make-order
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/product_order?allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=America/Sao_Paulo
    username: root
    password: